bind 127.0.0.1
port 6391
protected-mode no
daemonize no
pidfile /tmp/redis-vemb-redis-bench.pid
logfile ""
dir /tmp
dbfilename redis-vemb-redis-bench.rdb
save ""
appendonly no
appendfilename redis-vemb-redis-bench.aof

vector-dimension 300
